CFILES = srcs/data.c srcs/digit.c srcs/main.c srcs/util.c
INCLUDES = includes
OFILES = ${CFILES:.c=.o}
NAME = ft_number
FLAGS = -Wall -Wextra -Werror -g -fsanitize=address,undefined
CMD = cc

.c.o :
		${CMD} ${FLAGS} -c $< -o ${<:.c=.o} -I ${INCLUDES}

${NAME} : ${OFILES}
		${CMD} ${FLAGS} ${OFILES} -o ${NAME}


all : ${NAME}

clean :
		rm -f ${OFILES}

fclean :
		rm -f ${NAME} ${OFILES}

re : fclean all

 .PHONY:  all clean fclean re